build:
  environment:
    php: 7.4.7
    variables:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: xgallery_db
      DB_USERNAME: root
      DB_PASSWORD:
      MONGO_DB_HOST: 127.0.0.1
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABASE: xgallery_test
      MONGO_DB_USERNAME:
      MONGO_DB_PASSWORD:
      MONGO_DB_DSN: 'mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false'
  nodes:
    analysis:
      services:
        mongo: 4
        mysql: 5.7
  project_setup:
    before:
      - mysql -e "CREATE DATABASE xgallery_db"

