<?php

namespace Tests\Feature\Console\Command\Jav;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;
use Tests\Traits\FlickrMongoDatabase;

class R18Test extends TestCase
{
    use RefreshDatabase, FlickrMongoDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Queue::fake();
        Bus::fake();
    }
}
