name: CI

on: [pull_request]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout out
        uses: actions/checkout@v2
        if: success()
      - name: Composer
        run: composer install --no-interaction && composer update
      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.0
      - name: PHPStan
        run: php -d memory_limit=-1 vendor/bin/phpstan analyse app
