name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out
        uses: actions/checkout@v2
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
