name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out
        uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.4.0
        with:
          php-version: '7.4'
          tools: pecl
          extensions: imagick
  validate:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Composer
        run: composer install --prefer-dist
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
      - name: PHPStan
        uses: actions-x/phpstan@v1
      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.0
